###? Variables
@baseUrl = http://localhost:8000/api

@storeOwnerToken =


###! Store Owner
POST {{baseUrl}}/token/
Content-Type: application/json

{
  "username": "emma_brown",
  "password": "password123"
}



###? Create a new store
POST {{baseUrl}}/stores/
Authorization: Bearer {{storeOwnerToken}}
Content-Type: application/json

{
    "name": "002 emma_brown Test Store",
    "address": "123 Main oliver_garcia",
    "location": "City of emma_brown",
    "category_ids": [1,3,2,5]
}

###? Create a product

POST {{baseUrl}}/products/
Authorization: Bearer {{storeOwnerToken}}
Content-Type: application/json

{
    "name": "Store Owner Test Product 01 to store 4",
    "description": "Store Owner Test Product 01 to store num 6",
    "price": 9.99,
    "stock": 1,
    "brand_id": 2,
    "category_ids": [3, 2],
    "store_id": 4
}

###? Update a product

PUT {{baseUrl}}/products/38/
Authorization: Bearer {{storeOwnerToken}}
Content-Type: application/json

{
    "name": "S00",
    "description": "Store Owner Test Product 01 to store num 6",
    "price": 9.99,
    "stock": 1,
    "brand_id": 2,
    "category_ids": [3, 2],
    "store_id": 4
}
###? Get Details of a product

Get {{baseUrl}}/products/38/
Authorization: Bearer {{storeOwnerToken}}


###! Delete a product

DELETE  {{baseUrl}}/products/38/
Authorization: Bearer {{storeOwnerToken}}
Content-Type: application/json




###? Get my stores (store owners)
GET {{baseUrl}}/stores/
Authorization: Bearer {{storeOwnerToken}}

###? Get my stores (store owners)
GET {{baseUrl}}/products/my_products?page=1
Authorization: Bearer {{storeOwnerToken}}


###? Get specific store
GET {{baseUrl}}/stores/3/
Authorization: Bearer {{storeOwnerToken}}

###? Update store
PUT {{baseUrl}}/stores/3/
Authorization: Bearer {{storeOwnerToken}}
Content-Type: application/json

{
    "name": "Updated lucas perez Store",
    "address": "456 New Address",
    "location": "New Location",
    "category_ids": [1, 2]
}

###! Delete store
DELETE {{baseUrl}}/stores/6/
Authorization: Bearer {{storeOwnerToken}}


###? Get store orders
GET {{baseUrl}}/orders
Authorization: Bearer {{storeOwnerToken}}


###? Change order status (store owner)
PATCH {{baseUrl}}/orders/1ad1f9c6-4fc2-4dfd-9401-0e48373e64e1/update_status/
Content-Type: application/json
Authorization: Bearer {{storeOwnerToken}}

{
    "status": "Cancelled"
}


